version: 2.1
jobs:
  build-ike:
    working_directory: /go/src/github.com/maistra/istio-workspace
    docker:
      - image: cimg/go:1.17
    steps:
      - run: git clone https://github.com/maistra/istio-workspace .    
      - run: git checkout master
      - restore_cache:
          keys:
            - vendor-cache-{{ checksum "go.sum" }}

      - run: make tools
      - run: make deps compile ## we only care about the binary at this point

      - save_cache:
          key: vendor-cache-{{ checksum "go.sum" }}
          paths:
            - ./vendor
      - persist_to_workspace:
          ## We need ike binary while generating docs
          root: dist
          paths:
            - ike
  publish-docs:
    working_directory: /home/circleci/project
    docker:
      - image: circleci/node:10 # see https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Netlify CLI
          command: sudo npm install netlify-cli -g --unsafe-perm=true --allow-root
      - run:
          name: Install Dependencies
          command: |
            sudo npm install -g gulp --unsafe-perm=true --allow-root && npm install
            sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
      - run:
          name: Set up path
          command: |
            mv /home/circleci/project/dist/ike /home/circleci/project/dist/ike_latest
            echo 'export PATH=$PATH:${CIRCLE_WORKING_DIRECTORY}/dist:${CIRCLE_WORKING_DIRECTORY}/scripts' >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: Download released binaries
          command: download_releases.sh "/home/circleci/project/dist"
      - run:
          name: Build website
          command: npm run build
      - run:
          name: Deploy docs website to Netlify
          command: netlify deploy --dir docs --message "Built from Circle-CI $CIRCLE_BUILD_URL" --site $NETLIFY_SITE_ID --prod
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2.1
  docs:
    jobs:
      - build-ike
      - publish-docs:
          requires: 
            - build-ike
